# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/FPGA/PulseWidthCalc_ArtyS7/VHDL/UserFile.xdc

# Block Designs: bd/BlockDesignArtyS7/BlockDesignArtyS7.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlockDesignArtyS7 || ORIG_REF_NAME==BlockDesignArtyS7} -quiet] -quiet

# IP: bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_microblaze_0_0/BlockDesignArtyS7_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlockDesignArtyS7_microblaze_0_0 || ORIG_REF_NAME==BlockDesignArtyS7_microblaze_0_0} -quiet] -quiet

# IP: bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_dlmb_v10_0/BlockDesignArtyS7_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlockDesignArtyS7_dlmb_v10_0 || ORIG_REF_NAME==BlockDesignArtyS7_dlmb_v10_0} -quiet] -quiet

# IP: bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_ilmb_v10_0/BlockDesignArtyS7_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlockDesignArtyS7_ilmb_v10_0 || ORIG_REF_NAME==BlockDesignArtyS7_ilmb_v10_0} -quiet] -quiet

# IP: bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_dlmb_bram_if_cntlr_0/BlockDesignArtyS7_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlockDesignArtyS7_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==BlockDesignArtyS7_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_ilmb_bram_if_cntlr_0/BlockDesignArtyS7_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlockDesignArtyS7_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==BlockDesignArtyS7_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_lmb_bram_0/BlockDesignArtyS7_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlockDesignArtyS7_lmb_bram_0 || ORIG_REF_NAME==BlockDesignArtyS7_lmb_bram_0} -quiet] -quiet

# IP: bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_microblaze_0_axi_periph_0/BlockDesignArtyS7_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlockDesignArtyS7_microblaze_0_axi_periph_0 || ORIG_REF_NAME==BlockDesignArtyS7_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_microblaze_0_axi_intc_0/BlockDesignArtyS7_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlockDesignArtyS7_microblaze_0_axi_intc_0 || ORIG_REF_NAME==BlockDesignArtyS7_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_microblaze_0_xlconcat_0/BlockDesignArtyS7_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlockDesignArtyS7_microblaze_0_xlconcat_0 || ORIG_REF_NAME==BlockDesignArtyS7_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_mdm_1_0/BlockDesignArtyS7_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlockDesignArtyS7_mdm_1_0 || ORIG_REF_NAME==BlockDesignArtyS7_mdm_1_0} -quiet] -quiet

# IP: bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_clk_wiz_1_0/BlockDesignArtyS7_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlockDesignArtyS7_clk_wiz_1_0 || ORIG_REF_NAME==BlockDesignArtyS7_clk_wiz_1_0} -quiet] -quiet

# IP: bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_rst_clk_wiz_1_100M_0/BlockDesignArtyS7_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlockDesignArtyS7_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==BlockDesignArtyS7_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_axi_uartlite_0_0/BlockDesignArtyS7_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlockDesignArtyS7_axi_uartlite_0_0 || ORIG_REF_NAME==BlockDesignArtyS7_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_GPIOs_0_0/BlockDesignArtyS7_GPIOs_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlockDesignArtyS7_GPIOs_0_0 || ORIG_REF_NAME==BlockDesignArtyS7_GPIOs_0_0} -quiet] -quiet

# IP: bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_FastPulseWidthCalc_0_1/BlockDesignArtyS7_FastPulseWidthCalc_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlockDesignArtyS7_FastPulseWidthCalc_0_1 || ORIG_REF_NAME==BlockDesignArtyS7_FastPulseWidthCalc_0_1} -quiet] -quiet

# IP: bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_xbar_0/BlockDesignArtyS7_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlockDesignArtyS7_xbar_0 || ORIG_REF_NAME==BlockDesignArtyS7_xbar_0} -quiet] -quiet

# XDC: bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_microblaze_0_0/BlockDesignArtyS7_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BlockDesignArtyS7_microblaze_0_0 || ORIG_REF_NAME==BlockDesignArtyS7_microblaze_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_microblaze_0_0/BlockDesignArtyS7_microblaze_0_0_ooc_debug.xdc

# XDC: bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_microblaze_0_0/BlockDesignArtyS7_microblaze_0_0_ooc.xdc

# XDC: bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_dlmb_v10_0/BlockDesignArtyS7_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BlockDesignArtyS7_dlmb_v10_0 || ORIG_REF_NAME==BlockDesignArtyS7_dlmb_v10_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_dlmb_v10_0/BlockDesignArtyS7_dlmb_v10_0_ooc.xdc

# XDC: bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_ilmb_v10_0/BlockDesignArtyS7_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BlockDesignArtyS7_ilmb_v10_0 || ORIG_REF_NAME==BlockDesignArtyS7_ilmb_v10_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_ilmb_v10_0/BlockDesignArtyS7_ilmb_v10_0_ooc.xdc

# XDC: bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_dlmb_bram_if_cntlr_0/BlockDesignArtyS7_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_ilmb_bram_if_cntlr_0/BlockDesignArtyS7_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_lmb_bram_0/BlockDesignArtyS7_lmb_bram_0_ooc.xdc

# XDC: bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_microblaze_0_axi_intc_0/BlockDesignArtyS7_microblaze_0_axi_intc_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BlockDesignArtyS7_microblaze_0_axi_intc_0 || ORIG_REF_NAME==BlockDesignArtyS7_microblaze_0_axi_intc_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_microblaze_0_axi_intc_0/BlockDesignArtyS7_microblaze_0_axi_intc_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BlockDesignArtyS7_microblaze_0_axi_intc_0 || ORIG_REF_NAME==BlockDesignArtyS7_microblaze_0_axi_intc_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_microblaze_0_axi_intc_0/BlockDesignArtyS7_microblaze_0_axi_intc_0_ooc.xdc

# XDC: bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_mdm_1_0/BlockDesignArtyS7_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BlockDesignArtyS7_mdm_1_0 || ORIG_REF_NAME==BlockDesignArtyS7_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_mdm_1_0/BlockDesignArtyS7_mdm_1_0_ooc_trace.xdc

# XDC: bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_clk_wiz_1_0/BlockDesignArtyS7_clk_wiz_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BlockDesignArtyS7_clk_wiz_1_0 || ORIG_REF_NAME==BlockDesignArtyS7_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_clk_wiz_1_0/BlockDesignArtyS7_clk_wiz_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BlockDesignArtyS7_clk_wiz_1_0 || ORIG_REF_NAME==BlockDesignArtyS7_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_clk_wiz_1_0/BlockDesignArtyS7_clk_wiz_1_0_ooc.xdc

# XDC: bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_rst_clk_wiz_1_100M_0/BlockDesignArtyS7_rst_clk_wiz_1_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BlockDesignArtyS7_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==BlockDesignArtyS7_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_rst_clk_wiz_1_100M_0/BlockDesignArtyS7_rst_clk_wiz_1_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BlockDesignArtyS7_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==BlockDesignArtyS7_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_rst_clk_wiz_1_100M_0/BlockDesignArtyS7_rst_clk_wiz_1_100M_0_ooc.xdc

# XDC: bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_axi_uartlite_0_0/BlockDesignArtyS7_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BlockDesignArtyS7_axi_uartlite_0_0 || ORIG_REF_NAME==BlockDesignArtyS7_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_axi_uartlite_0_0/BlockDesignArtyS7_axi_uartlite_0_0_ooc.xdc

# XDC: bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_axi_uartlite_0_0/BlockDesignArtyS7_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BlockDesignArtyS7_axi_uartlite_0_0 || ORIG_REF_NAME==BlockDesignArtyS7_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_xbar_0/BlockDesignArtyS7_xbar_0_ooc.xdc

# XDC: bd/BlockDesignArtyS7/BlockDesignArtyS7_ooc.xdc
