# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7s50csga324-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/FPGA/PulseWidthCalc_ArtyS7/PulseWidthCalc_ArtyS7.cache/wt [current_project]
set_property parent.project_path C:/FPGA/PulseWidthCalc_ArtyS7/PulseWidthCalc_ArtyS7.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths {
  c:/FPGA/ip_repo/PulseIP_1.0
  c:/FPGA/ip_repo/FastPulseWidthCalc_1.0
} [current_project]
update_ip_catalog
set_property ip_output_repo c:/FPGA/PulseWidthCalc_ArtyS7/PulseWidthCalc_ArtyS7.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/FPGA/PulseWidthCalc_ArtyS7/VHDL/Led.vhd
  C:/FPGA/PulseWidthCalc_ArtyS7/PulseWidthCalc_ArtyS7.srcs/sources_1/bd/BlockDesignArtyS7/hdl/BlockDesignArtyS7_wrapper.vhd
}
add_files C:/FPGA/PulseWidthCalc_ArtyS7/PulseWidthCalc_ArtyS7.srcs/sources_1/bd/BlockDesignArtyS7/BlockDesignArtyS7.bd
set_property used_in_implementation false [get_files -all c:/FPGA/PulseWidthCalc_ArtyS7/PulseWidthCalc_ArtyS7.srcs/sources_1/bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_microblaze_0_0/BlockDesignArtyS7_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA/PulseWidthCalc_ArtyS7/PulseWidthCalc_ArtyS7.srcs/sources_1/bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_microblaze_0_0/BlockDesignArtyS7_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA/PulseWidthCalc_ArtyS7/PulseWidthCalc_ArtyS7.srcs/sources_1/bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_microblaze_0_0/BlockDesignArtyS7_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA/PulseWidthCalc_ArtyS7/PulseWidthCalc_ArtyS7.srcs/sources_1/bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_dlmb_v10_0/BlockDesignArtyS7_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA/PulseWidthCalc_ArtyS7/PulseWidthCalc_ArtyS7.srcs/sources_1/bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_dlmb_v10_0/BlockDesignArtyS7_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA/PulseWidthCalc_ArtyS7/PulseWidthCalc_ArtyS7.srcs/sources_1/bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_ilmb_v10_0/BlockDesignArtyS7_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA/PulseWidthCalc_ArtyS7/PulseWidthCalc_ArtyS7.srcs/sources_1/bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_ilmb_v10_0/BlockDesignArtyS7_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA/PulseWidthCalc_ArtyS7/PulseWidthCalc_ArtyS7.srcs/sources_1/bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_dlmb_bram_if_cntlr_0/BlockDesignArtyS7_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA/PulseWidthCalc_ArtyS7/PulseWidthCalc_ArtyS7.srcs/sources_1/bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_ilmb_bram_if_cntlr_0/BlockDesignArtyS7_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA/PulseWidthCalc_ArtyS7/PulseWidthCalc_ArtyS7.srcs/sources_1/bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_lmb_bram_0/BlockDesignArtyS7_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA/PulseWidthCalc_ArtyS7/PulseWidthCalc_ArtyS7.srcs/sources_1/bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_microblaze_0_axi_intc_0/BlockDesignArtyS7_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA/PulseWidthCalc_ArtyS7/PulseWidthCalc_ArtyS7.srcs/sources_1/bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_microblaze_0_axi_intc_0/BlockDesignArtyS7_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA/PulseWidthCalc_ArtyS7/PulseWidthCalc_ArtyS7.srcs/sources_1/bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_microblaze_0_axi_intc_0/BlockDesignArtyS7_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA/PulseWidthCalc_ArtyS7/PulseWidthCalc_ArtyS7.srcs/sources_1/bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_clk_wiz_1_0/BlockDesignArtyS7_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA/PulseWidthCalc_ArtyS7/PulseWidthCalc_ArtyS7.srcs/sources_1/bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_clk_wiz_1_0/BlockDesignArtyS7_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA/PulseWidthCalc_ArtyS7/PulseWidthCalc_ArtyS7.srcs/sources_1/bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_clk_wiz_1_0/BlockDesignArtyS7_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA/PulseWidthCalc_ArtyS7/PulseWidthCalc_ArtyS7.srcs/sources_1/bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_rst_clk_wiz_1_100M_0/BlockDesignArtyS7_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA/PulseWidthCalc_ArtyS7/PulseWidthCalc_ArtyS7.srcs/sources_1/bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_rst_clk_wiz_1_100M_0/BlockDesignArtyS7_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA/PulseWidthCalc_ArtyS7/PulseWidthCalc_ArtyS7.srcs/sources_1/bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_rst_clk_wiz_1_100M_0/BlockDesignArtyS7_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA/PulseWidthCalc_ArtyS7/PulseWidthCalc_ArtyS7.srcs/sources_1/bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_axi_uartlite_0_0/BlockDesignArtyS7_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA/PulseWidthCalc_ArtyS7/PulseWidthCalc_ArtyS7.srcs/sources_1/bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_axi_uartlite_0_0/BlockDesignArtyS7_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA/PulseWidthCalc_ArtyS7/PulseWidthCalc_ArtyS7.srcs/sources_1/bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_axi_uartlite_0_0/BlockDesignArtyS7_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA/PulseWidthCalc_ArtyS7/PulseWidthCalc_ArtyS7.srcs/sources_1/bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_xbar_0/BlockDesignArtyS7_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA/PulseWidthCalc_ArtyS7/PulseWidthCalc_ArtyS7.srcs/sources_1/bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_mdm_0_0/BlockDesignArtyS7_mdm_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA/PulseWidthCalc_ArtyS7/PulseWidthCalc_ArtyS7.srcs/sources_1/bd/BlockDesignArtyS7/ip/BlockDesignArtyS7_mdm_0_0/BlockDesignArtyS7_mdm_0_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all C:/FPGA/PulseWidthCalc_ArtyS7/PulseWidthCalc_ArtyS7.srcs/sources_1/bd/BlockDesignArtyS7/BlockDesignArtyS7_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/FPGA/PulseWidthCalc_ArtyS7/VHDL/UserFile.xdc
set_property used_in_implementation false [get_files C:/FPGA/PulseWidthCalc_ArtyS7/VHDL/UserFile.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top BlockDesignArtyS7_wrapper -part xc7s50csga324-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef BlockDesignArtyS7_wrapper.dcp
create_report "synth_3_synth_report_utilization_0" "report_utilization -file BlockDesignArtyS7_wrapper_utilization_synth.rpt -pb BlockDesignArtyS7_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
